"""
fix_v60_pipeline.py — Fix the V60 pipeline to generate train+test features
with identical column sets.

Problem: features_clean_v60.parquet only has 450 training rows.
test_features_clean_v60.parquet was generated by a different script
with different columns → 25 common only → V304 OOF 0.646 (vs V303 0.587).

Solution: Create a single pipeline that generates train_features_clean_v60.parquet
and test_features_clean_v60.parquet using the EXACT same feature columns.
"""
import re, json, warnings, time, gc
from pathlib import Path
import numpy as np
import pandas as pd
from datetime import datetime

warnings.filterwarnings('ignore')

ROOT = Path('/home/mwoo423/.openclaw/workspace')
DATA = ROOT / 'data_processed'
DATA_RAW = ROOT / 'data_raw' / 'ch2025_data_items'
SAMPLE_CSV = DATA_RAW.parent / 'ch2026_submission_sample.csv'
LABEL_CSV = DATA_RAW.parent / 'ch2026_metrics_train.csv'

TARGETS = {'Q1','Q2','Q3','S1','S2','S3','S4'}
META_COLS = {'subject_id','lifelog_date','sleep_date','date'}

PARQUET_FILES = {
    'mACStatus':    'ch2025_mACStatus.parquet',
    'mActivity':    'ch2025_mActivity.parquet',
    'mAmbience':    'ch2025_mAmbience.parquet',
    'mBle':         'ch2025_mBle.parquet',
    'mGps':         'ch2025_mGps.parquet',
    'mLight':       'ch2025_mLight.parquet',
    'mScreenStatus': 'ch2025_mScreenStatus.parquet',
    'mUsageStats':  'ch2025_mUsageStats.parquet',
    'mWifi':        'ch2025_mWifi.parquet',
    'wHr':          'ch2025_wHr.parquet',
    'wLight':       'ch2025_wLight.parquet',
    'wPedo':        'ch2025_wPedo.parquet',
}

AGG_FUNCS = ['mean', 'std', 'min', 'max', 'count']

def parse_json_array(val):
    """Parse numpy ndarray of [category, value] pairs (already parsed by parquet reader)."""
    if val is None:
        return {}
    if not isinstance(val, np.ndarray):
        return {}
    result = {}
    for item in val:
        if isinstance(item, (np.ndarray, list)) and len(item) >= 2:
            category = str(item[0])
            try:
                value = float(item[1])
            except:
                value = 0.0
            result[category] = value
    return result

def parse_json_objects(val):
    """Parse numpy ndarray of dict objects."""
    if val is None:
        return []
    if not isinstance(val, np.ndarray):
        return []
    result = []
    for item in val:
        if isinstance(item, dict):
            result.append(item)
    return result

def build_device_features(df, device_name):
    """Build features from a single device's data for all subjects and dates."""
    if df.empty:
        return pd.DataFrame()
    
    df = df.copy()
    
    if 'timestamp' in df.columns and 'date' not in df.columns:
        df['timestamp'] = pd.to_datetime(df['timestamp'])
        df['date'] = df['timestamp'].dt.date
    
    if 'date' not in df.columns:
        return pd.DataFrame()
    
    agg_dfs = []
    
    # Special handling for JSON-based devices
    if device_name == 'mAmbience':
        if 'm_ambience' in df.columns:
            records = []
            for _, row in df.iterrows():
                parsed = parse_json_array(row['m_ambience'])
                for category, value in parsed.items():
                    records.append({
                        'subject_id': row['subject_id'],
                        'date': row['date'],
                        'ambience_category': category,
                        'ambience_value': value,
                    })
            if records:
                amb_df = pd.DataFrame(records)
                agg = amb_df.groupby(['subject_id', 'date', 'ambience_category'])['ambience_value'].sum().reset_index()
                pivoted = agg.pivot_table(index=['subject_id', 'date'], 
                                          columns='ambience_category', 
                                          values='ambience_value', 
                                          fill_value=0)
                pivoted.columns = [f'mAmbience_ambience_{col}_sum' for col in pivoted.columns]
                pivoted = pivoted.reset_index()
                return pivoted
        return pd.DataFrame()
    
    if device_name == 'mBle':
        # BLE: list of {address, device_class, rssi}
        if 'm_ble' in df.columns:
            records = []
            for _, row in df.iterrows():
                parsed = parse_json_objects(row['m_ble'])
                for item in parsed:
                    records.append({
                        'subject_id': row['subject_id'],
                        'date': row['date'],
                        'rssi': item.get('rssi', 0),
                        'device_class': item.get('device_class', '0'),
                        'address': item.get('address', ''),
                    })
            if records:
                ble_df = pd.DataFrame(records)
                agg = ble_df.groupby(['subject_id', 'date'])['rssi'].agg(['mean', 'std', 'min', 'max']).reset_index()
                agg.columns = ['subject_id', 'date', 'mBle_ble_avg_rssi_mean', 'mBle_ble_avg_rssi_std', 
                              'mBle_ble_avg_rssi_min', 'mBle_ble_avg_rssi_max']
                agg_dfs.append(agg)
                
                max_rssi = ble_df.groupby(['subject_id', 'date'])['rssi'].agg(['max', 'std']).reset_index()
                max_rssi.columns = ['subject_id', 'date', 'mBle_ble_max_rssi_mean', 'mBle_ble_max_rssi_std']
                agg_dfs.append(max_rssi)
                
                min_rssi = ble_df.groupby(['subject_id', 'date'])['rssi'].agg(['min', 'std']).reset_index()
                min_rssi.columns = ['subject_id', 'date', 'mBle_ble_min_rssi_mean', 'mBle_ble_min_rssi_std']
                agg_dfs.append(min_rssi)
                
                rssi_std = ble_df.groupby(['subject_id', 'date'])['rssi'].agg(['std']).reset_index()
                rssi_std.columns = ['subject_id', 'date', 'mBle_ble_rssi_std_mean']
                agg_dfs.append(rssi_std)
                
                device_count = ble_df.groupby(['subject_id', 'date'])['address'].nunique().reset_index()
                device_count.columns = ['subject_id', 'date', 'mBle_ble_device_count_mean']
                agg_dfs.append(device_count)
                
                ble_count = ble_df.groupby(['subject_id', 'date']).size().reset_index(name='mBle_ble_count_mean')
                agg_dfs.append(ble_count)
                
                # skip duplicate device_count stats to avoid column mismatch
                return agg_dfs[0] if len(agg_dfs) == 1 else pd.concat(agg_dfs, axis=1)
        return pd.DataFrame()
    
    if device_name == 'mGps':
        # GPS: list of {altitude, latitude, longitude, speed}
        if 'm_gps' in df.columns:
            records = []
            for _, row in df.iterrows():
                parsed = parse_json_objects(row['m_gps'])
                for item in parsed:
                    records.append({
                        'subject_id': row['subject_id'],
                        'date': row['date'],
                        'speed': item.get('speed', 0),
                        'altitude': item.get('altitude', 0),
                        'latitude': item.get('latitude', 0),
                        'longitude': item.get('longitude', 0),
                    })
            if records:
                gps_df = pd.DataFrame(records)
                for col_name, feat_name in [('speed', 'gps_speed'), ('altitude', 'gps_alt')]:
                    agg = gps_df.groupby(['subject_id', 'date'])[col_name].agg(['mean', 'std', 'max', 'min']).reset_index()
                    agg.columns = ['subject_id', 'date', 
                                  f'mGps_{feat_name}_mean', f'mGps_{feat_name}_std',
                                  f'mGps_{feat_name}_max', f'mGps_{feat_name}_min']
                    agg_dfs.append(agg)
                
                gps_count = gps_df.groupby(['subject_id', 'date']).size().reset_index(name='mGps_gps_count_mean')
                agg_dfs.append(gps_count)
                
                has_speed = gps_df[['subject_id', 'date']].copy()
                has_speed['has_speed'] = (gps_df['speed'] > 0).astype(int)
                has_speed_agg = has_speed.groupby(['subject_id', 'date'])['has_speed'].agg(['mean', 'std', 'max', 'min']).reset_index()
                has_speed_agg.columns = ['subject_id', 'date', 'mGps_gps_has_speed_mean', 'mGps_gps_has_speed_std',
                                        'mGps_gps_has_speed_max', 'mGps_gps_has_speed_min']
                agg_dfs.append(has_speed_agg)
                
                return agg_dfs[0] if len(agg_dfs) == 1 else pd.concat(agg_dfs, axis=1)
        return pd.DataFrame()
    
    if device_name == 'mUsageStats':
        # UsageStats: list of {app_name, total_time, category, ratio}
        if 'm_usage_stats' in df.columns:
            records = []
            for _, row in df.iterrows():
                parsed = parse_json_objects(row['m_usage_stats'])
                for item in parsed:
                    records.append({
                        'subject_id': row['subject_id'],
                        'date': row['date'],
                        'app_name': item.get('app_name', ''),
                        'total_time': item.get('total_time', 0),
                        'category': item.get('category', ''),
                        'ratio': item.get('ratio', 0),
                    })
            if records:
                us_df = pd.DataFrame(records)
                
                # Ratio features
                ratio_agg = us_df.groupby(['subject_id', 'date'])['ratio'].agg(['mean', 'std', 'max']).reset_index()
                ratio_agg.columns = ['subject_id', 'date', 'mUsageStats_usage_ratio_mean', 
                                    'mUsageStats_usage_ratio_std', 'mUsageStats_usage_ratio_max']
                agg_dfs.append(ratio_agg)
                
                # Time features
                time_agg = us_df.groupby(['subject_id', 'date'])['total_time'].agg(['sum', 'mean']).reset_index()
                time_agg.columns = ['subject_id', 'date', 'mUsageStats_usage_total_time_sum', 
                                   'mUsageStats_usage_total_time_mean']
                agg_dfs.append(time_agg)
                
                # Category ratio
                cat_agg = us_df.groupby(['subject_id', 'date', 'category'])['ratio'].sum().reset_index()
                pivoted = cat_agg.pivot_table(index=['subject_id', 'date'], columns='category', 
                                              values='ratio', fill_value=0)
                pivoted.columns = [f'mUsageStats_usage_{col}_ratio_sum' for col in pivoted.columns]
                pivoted = pivoted.reset_index()
                agg_dfs.append(pivoted)
                
                return agg_dfs[0] if len(agg_dfs) == 1 else pd.concat(agg_dfs, axis=1)
        return pd.DataFrame()
    
    if device_name == 'mWifi':
        # WiFi: list of {bssid, rssi}
        if 'm_wifi' in df.columns:
            records = []
            for _, row in df.iterrows():
                parsed = parse_json_objects(row['m_wifi'])
                for item in parsed:
                    records.append({
                        'subject_id': row['subject_id'],
                        'date': row['date'],
                        'bssid': item.get('bssid', ''),
                        'rssi': item.get('rssi', 0),
                    })
            if records:
                wifi_df = pd.DataFrame(records)
                
                # RSSI features
                rssi_agg = wifi_df.groupby(['subject_id', 'date'])['rssi'].agg(['mean', 'std', 'min', 'max']).reset_index()
                rssi_agg.columns = ['subject_id', 'date', 'mWifi_wifi_avg_rssi_mean', 
                                   'mWifi_wifi_avg_rssi_std', 'mWifi_wifi_avg_rssi_min', 'mWifi_wifi_avg_rssi_max']
                agg_dfs.append(rssi_agg)
                
                # Max RSSI
                max_rssi = wifi_df.groupby(['subject_id', 'date'])['rssi'].agg(['max']).reset_index()
                max_rssi.columns = ['subject_id', 'date', 'mWifi_wifi_max_rssi_mean']
                agg_dfs.append(max_rssi)
                
                # Strong signal ratio (RSSI >= -60)
                strong = wifi_df[['subject_id', 'date']].copy()
                strong['is_strong'] = (wifi_df['rssi'] >= -60).astype(int)
                strong_agg = strong.groupby(['subject_id', 'date'])['is_strong'].mean().reset_index()
                strong_agg.columns = ['subject_id', 'date', 'mWifi_wifi_strong_ratio_mean']
                agg_dfs.append(strong_agg)
                
                # BSSID count (unique networks)
                bssid_agg = wifi_df.groupby(['subject_id', 'date'])['bssid'].nunique().reset_index()
                bssid_agg.columns = ['subject_id', 'date', 'mWifi_wifi_bssid_count_mean']
                agg_dfs.append(bssid_agg)
                
                # WiFi count
                wifi_count = wifi_df.groupby(['subject_id', 'date']).size().reset_index(name='mWifi_wifi_count_mean')
                agg_dfs.append(wifi_count)
                
                return agg_dfs[0] if len(agg_dfs) == 1 else pd.concat(agg_dfs, axis=1)
        return pd.DataFrame()
    
    # Standard numeric aggregation for other devices
    numeric_cols = []
    for col in df.columns:
        if col in ['subject_id', 'date', 'timestamp']:
            continue
        if df[col].dtype in [np.float64, np.int64, float, int, bool, np.bool_]:
            numeric_cols.append(col)
    
    if not numeric_cols:
        return pd.DataFrame()
    
    agg_dfs = []
    for col in numeric_cols:
        col_name = f'{device_name}_{col}'
        for agg_func in AGG_FUNCS:
            agg_col = f'{col_name}_{agg_func}'
            result = df.groupby(['subject_id', 'date'])[col].agg(agg_func).reset_index()
            result.columns = ['subject_id', 'date', agg_col]
            agg_dfs.append(result)
    
    if not agg_dfs:
        return pd.DataFrame()
    
    result = agg_dfs[0]
    for df2 in agg_dfs[1:]:
        result = result.merge(df2, on=['subject_id', 'date'], how='left')
    
    return result

def build_time_bin_features(df, device_name):
    """Build hour-of-day bin features (morning/afternoon/evening/night)."""
    if 'hour' not in df.columns:
        return pd.DataFrame()
    
    def bin_hour(h):
        if h < 6: return 'night'
        elif h < 12: return 'morning'
        elif h < 18: return 'afternoon'
        else: return 'evening'
    
    df['time_bin'] = df['hour'].apply(bin_hour)
    time_agg = df.groupby(["subject_id", "date", "time_bin"]).size().unstack(fill_value=0)
    time_agg.columns = [f'{device_name.lower().replace("status","")}_hour_{col}' for col in time_agg.columns]
    time_agg = time_agg.reset_index()
    return time_agg

def generate_features_for_subjects(subjects, label_df=None):
    """Generate features for given subjects. Returns DataFrame with identical columns regardless of subjects."""
    print(f"  Processing subjects: {sorted(subjects)[:5]}... ({len(subjects)} total)")
    
    # Start with subject+date key
    feature_dfs = []
    
    for device_name, fname in PARQUET_FILES.items():
        path = DATA_RAW / fname
        if not path.exists():
            print(f"    Skipping {fname}")
            continue
        
        print(f"    Loading {fname}...")
        df = pd.read_parquet(path)
        
        # Filter to target subjects
        df = df[df['subject_id'].isin(subjects)].copy()
        
        if df.empty:
            print(f"      Empty for target subjects, skipping")
            continue
        
        print(f"      Shape: {df.shape}")
        
        # Parse datetime
        if 'timestamp' in df.columns:
            df['timestamp'] = pd.to_datetime(df['timestamp'])
            df['date'] = df['timestamp'].dt.date
            df['hour'] = df['timestamp'].dt.hour
        
        # Build device features
        dev_df = build_device_features(df, device_name)
        
        if not dev_df.empty:
            feature_dfs.append(dev_df)
        
        # Time bin features for ACStatus and ScreenStatus
        if device_name in ('mACStatus', 'mScreenStatus') and 'hour' in df.columns:
            time_df = build_time_bin_features(df, device_name)
            if not time_df.empty:
                feature_dfs.append(time_df)
        
        del df
        gc.collect()
    
    if not feature_dfs:
        return pd.DataFrame()
    
    # Merge all features — handle duplicate column names
    # Start with full key table (all subject_id + date combos for target subjects)
    key_df = pd.DataFrame({
        'subject_id': sorted(subjects),
        'date': [pd.date_range(pd.Timestamp.min.date(), pd.Timestamp.now().date()).date] * 1
    })
    # Actually build proper key from first feature df or from labels
    # Build a full cartesian key
    all_dates = set()
    for fdf in feature_dfs:
        if 'date' in fdf.columns and 'subject_id' in fdf.columns:
            for sid, dt in zip(fdf['subject_id'].values, fdf['date'].values):
                all_dates.add((sid, dt))
    if all_dates:
        key_df = pd.DataFrame(list(all_dates), columns=['subject_id', 'date'])
    
    # Merge progressively with suffixes for potential duplicates
    result = key_df.copy()
    seen_cols = set(result.columns)
    for idx, df in enumerate(feature_dfs):
        # Rename duplicate columns
        rename_map = {}
        for col in df.columns:
            if col in seen_cols:
                rename_map[col] = f'{col}_v{idx}'
        df = df.rename(columns=rename_map)
        result = result.merge(df, on=['subject_id', 'date'], how='left')
        seen_cols.update(df.columns)
    
    result = result.fillna(0)
    
    # Add labels if provided
    if label_df is not None:
        label_df = label_df.copy()
        label_df['date'] = pd.to_datetime(label_df['lifelog_date']).dt.date
        result = result.merge(label_df[['subject_id', 'date', 'sleep_date', 'lifelog_date'] + TARGETS.tolist()], 
                             on=['subject_id', 'date'], how='left')
    
    return result

def main():
    t0 = time.time()
    print("=" * 70)
    print("fix_v60_pipeline.py — Generate train+test features with identical columns")
    print("=" * 70)
    
    # Load labels
    print("\nLoading labels...")
    labels = pd.read_csv(LABEL_CSV, parse_dates=['sleep_date', 'lifelog_date'])
    print(f"  Labels: {labels.shape}")
    
    # Load sample for test dates
    print("Loading submission sample...")
    sample = pd.read_csv(SAMPLE_CSV, parse_dates=['sleep_date', 'lifelog_date'])
    sample['date'] = sample['lifelog_date'].dt.date
    print(f"  Sample: {sample.shape}")
    
    # All subjects
    all_subjects = set(labels['subject_id'].unique()) | set(sample['subject_id'].unique())
    print(f"\nAll subjects: {sorted(all_subjects)}")
    
    # Generate train features
    print("\n── Generating train features ──")
    train_subjects = set(labels['subject_id'].unique())
    train_feat = generate_features_for_subjects(train_subjects, label_df=labels)
    print(f"Train shape: {train_feat.shape}")
    
    # Generate test features
    print("\n── Generating test features ──")
    test_subjects = set(sample['subject_id'].unique())
    test_feat = generate_features_for_subjects(test_subjects, label_df=None)
    
    # Merge sleep_date and lifelog_date from sample
    sample_key = sample[['subject_id', 'date', 'sleep_date', 'lifelog_date']]
    test_feat = test_feat.merge(sample_key, on=['subject_id', 'date'], how='left')
    print(f"Test shape: {test_feat.shape}")
    
    # Compare columns
    train_cols = sorted([c for c in train_feat.columns if c not in META_COLS | set(TARGETS)])
    test_cols = sorted([c for c in test_feat.columns if c not in META_COLS | set(TARGETS)])
    common_cols = sorted(set(train_cols) & set(test_cols))
    
    print(f"\nTrain features: {len(train_cols)}")
    print(f"Test features: {len(test_cols)}")
    print(f"Common features: {len(common_cols)}")
    
    if set(train_cols) != set(test_cols):
        missing_in_test = sorted(set(train_cols) - set(test_cols))
        extra_in_test = sorted(set(test_cols) - set(train_cols))
        print(f"\nMissing in test: {len(missing_in_test)}")
        if missing_in_test:
            for c in missing_in_test[:10]:
                print(f"  {c}")
        print(f"\nExtra in test: {len(extra_in_test)}")
        if extra_in_test:
            for c in extra_in_test[:10]:
                print(f"  {c}")
    
    # Save
    train_path = DATA / 'train_features_clean_v60.parquet'
    test_path = DATA / 'test_features_clean_v60.parquet'
    
    train_feat.to_parquet(train_path, index=False)
    test_feat.to_parquet(test_path, index=False)
    
    print(f"\nSaved:")
    print(f"  Train: {train_path}")
    print(f"  Test: {test_path}")
    print(f"\nTime: {time.time()-t0:.1f}s")

if __name__ == '__main__':
    main()
