"""
gen_v60_train_test.py — Generate train+test features with EXACT same columns.

Strategy: Use the EXACT same pipeline as 02_feature_engineering_v2.py for both
train and test, ensuring identical column sets.

Key insight: The issue is that test features were generated by a different
script (gen_test_features_v60.py) with different aggregation logic.
Now we use the SAME logic for both.
"""
import numpy as np
import pandas as pd
import json
import gc
import time
import warnings
warnings.filterwarnings('ignore')

from pathlib import Path

ROOT = Path('/home/mwoo423/.openclaw/workspace')
DATA = ROOT / 'data_processed'
DATA_RAW = ROOT / 'data_raw' / 'ch2025_data_items'
SAMPLE_CSV = DATA_RAW.parent / 'ch2026_submission_sample.csv'
LABEL_CSV = DATA_RAW.parent / 'ch2026_metrics_train.csv'

TARGETS = {'Q1','Q2','Q3','S1','S2','S3','S4'}
META_COLS = {'subject_id','lifelog_date','sleep_date','date'}

# ── Helper functions ──────────────────────────────────────────────────

def _safe_json_parse(val):
    """Parse JSON safely."""
    if pd.isna(val) or val == 'null':
        return None
    if isinstance(val, str):
        try:
            return json.loads(val)
        except:
            return None
    return val

def parse_json_columns(df, json_columns):
    """Convert JSON column to parsed dict."""
    for col in json_columns:
        if col in df.columns:
            df[col] = df[col].apply(_safe_json_parse)
    return df

def build_merge_key(df):
    """Ensure date/datetime columns are properly typed.
    Raw parquet uses 'timestamp' column, not 'datetime'."""
    df = df.copy()
    if 'date' in df.columns:
        df['date'] = pd.to_datetime(df['date']).dt.date
    if 'timestamp' in df.columns:
        df['timestamp'] = pd.to_datetime(df['timestamp'])
        if 'date' not in df.columns:
            df['date'] = df['timestamp'].dt.date
        if 'datetime' not in df.columns:
            df['datetime'] = df['timestamp']  # alias for compat with 02_feature_engineering
    elif 'datetime' in df.columns:
        df['datetime'] = pd.to_datetime(df['datetime'])
        if 'date' not in df.columns:
            df['date'] = df['datetime'].dt.date
    return df

def aggregate_numeric(df, data_col, agg_cols=['subject_id','date'], agg_funcs=None):
    """Aggregate numeric column."""
    if agg_funcs is None:
        agg_funcs = ['mean', 'std', 'min', 'max', 'count']
    grouped = df.groupby(agg_cols)[data_col].agg(agg_funcs)
    grouped.columns = [f"{data_col}_{f}" for f in agg_funcs]
    return grouped.reset_index()

# ── JSON device parsers ──────────────────────────────────────────────

def parse_ble(df):
    """Parse BLE data."""
    records = []
    for _, row in df.iterrows():
        val = row.get('ble')
        if pd.isna(val) or val == 'null':
            continue
        if isinstance(val, str):
            try: val = json.loads(val)
            except: continue
        if not isinstance(val, list):
            continue
        for item in val:
            if isinstance(item, dict):
                records.append({
                    'subject_id': row['subject_id'],
                    'datetime': row.get('datetime'),
                    'rssi': item.get('rssi'),
                    'device_count': item.get('deviceCount'),
                })
    if records:
        return pd.DataFrame(records)
    return pd.DataFrame(columns=['subject_id','datetime','rssi','device_count'])

def parse_gps(df):
    """Parse GPS data."""
    records = []
    for _, row in df.iterrows():
        val = row.get('gps')
        if pd.isna(val) or val == 'null':
            continue
        if isinstance(val, str):
            try: val = json.loads(val)
            except: continue
        if not isinstance(val, list):
            continue
        for item in val:
            if isinstance(item, dict):
                records.append({
                    'subject_id': row['subject_id'],
                    'datetime': row.get('datetime'),
                    'speed': item.get('speed'),
                    'altitude': item.get('altitude'),
                })
    if records:
        return pd.DataFrame(records)
    return pd.DataFrame(columns=['subject_id','datetime','speed','altitude'])

def parse_wifi(df):
    """Parse WiFi data."""
    records = []
    for _, row in df.iterrows():
        val = row.get('wifi')
        if pd.isna(val) or val == 'null':
            continue
        if isinstance(val, str):
            try: val = json.loads(val)
            except: continue
        if not isinstance(val, list):
            continue
        for item in val:
            if isinstance(item, dict):
                records.append({
                    'subject_id': row['subject_id'],
                    'datetime': row.get('datetime'),
                    'rssi': item.get('rssi'),
                    'bssid': item.get('bssid'),
                    'strength': item.get('strength'),
                })
    if records:
        return pd.DataFrame(records)
    return pd.DataFrame(columns=['subject_id','datetime','rssi','bssid','strength'])

def parse_ambience(df):
    """Parse ambience data."""
    records = []
    for _, row in df.iterrows():
        val = row['ambience']
        subj = row['subject_id']
        dt = row.get('datetime')

        if val is None:
            continue
        if isinstance(val, str):
            try: val = json.loads(val)
            except: continue
        if not isinstance(val, list):
            continue
        for item in val:
            if isinstance(item, dict) and 'value' in item:
                records.append({
                    'subject_id': subj,
                    'datetime': dt,
                    'ambience_value': item['value'],
                })
    if records:
        return pd.DataFrame(records)
    return pd.DataFrame(columns=['subject_id','datetime','ambience_value'])

def parse_usage_stats(df):
    """Parse UsageStats data."""
    records = []
    for _, row in df.iterrows():
        val = row.get('usage')
        if pd.isna(val) or val == 'null':
            continue
        if isinstance(val, str):
            try: val = json.loads(val)
            except: continue
        if not isinstance(val, list):
            continue
        for item in val:
            if isinstance(item, dict):
                records.append({
                    'subject_id': row['subject_id'],
                    'datetime': row.get('datetime'),
                    'app_name': item.get('app_name',''),
                    'total_time': item.get('total_time', 0),
                    'category': item.get('category',''),
                    'ratio': item.get('ratio', 0),
                })
    if records:
        return pd.DataFrame(records)
    return pd.DataFrame(columns=['subject_id','datetime','app_name','total_time','category','ratio'])

def parse_screen_use(df):
    """Parse screen_use dict from mScreenStatus."""
    records = []
    for _, row in df.iterrows():
        val = row.get('screen_use')
        if isinstance(val, dict):
            records.append({
                'subject_id': row['subject_id'],
                'datetime': row.get('datetime'),
                'screen_use': val.get('screen_use', 0),
            })
        else:
            # Already numeric
            records.append({
                'subject_id': row['subject_id'],
                'datetime': row.get('datetime'),
                'screen_use': val,
            })
    if records:
        return pd.DataFrame(records)
    return pd.DataFrame(columns=['subject_id','datetime','screen_use'])

# ── Feature building ─────────────────────────────────────────────────

def load_and_filter_parquet(subject_ids):
    """Load parquet files and filter to target subjects."""
    PARQUET_FILES = {
        'mACStatus': 'ch2025_mACStatus.parquet',
        'mActivity': 'ch2025_mActivity.parquet',
        'mAmbience': 'ch2025_mAmbience.parquet',
        'mBle': 'ch2025_mBle.parquet',
        'mGps': 'ch2025_mGps.parquet',
        'mLight': 'ch2025_mLight.parquet',
        'mScreenStatus': 'ch2025_mScreenStatus.parquet',
        'mUsageStats': 'ch2025_mUsageStats.parquet',
        'mWifi': 'ch2025_mWifi.parquet',
        'wHr': 'ch2025_wHr.parquet',
        'wLight': 'ch2025_wLight.parquet',
        'wPedo': 'ch2025_wPedo.parquet',
    }
    
    parquet_dfs = {}
    for name, filename in PARQUET_FILES.items():
        path = DATA_RAW / filename
        if not path.exists():
            continue
        df = pd.read_parquet(path)
        df = df[df['subject_id'].isin(subject_ids)].copy()
        if df.empty:
            continue
        parquet_dfs[name] = build_merge_key(df)
    return parquet_dfs

def create_day_features(parquet_dfs, labels=None):
    """Create day-level features for given subjects (same as 02_feature_engineering_v2.py)."""
    feature_dfs = []
    
    # ── 1. Numeric columns aggregation ──
    # mACStatus: m_charging, m_screen_use
    if 'mACStatus' in parquet_dfs:
        df = parquet_dfs['mACStatus'].copy()
        if 'm_charging' in df.columns:
            agg = aggregate_numeric(df, 'm_charging')
            agg.columns = ['subject_id','date','mACStatus_m_charging_mean','mACStatus_m_charging_std',
                          'mACStatus_m_charging_min','mACStatus_m_charging_max','mACStatus_m_charging_count']
            feature_dfs.append(agg)
    
    # mActivity: m_activity
    if 'mActivity' in parquet_dfs:
        df = parquet_dfs['mActivity'].copy()
        if 'm_activity' in df.columns:
            agg = aggregate_numeric(df, 'm_activity')
            agg.columns = ['subject_id','date','mActivity_m_activity_mean','mActivity_m_activity_std',
                          'mActivity_m_activity_min','mActivity_m_activity_max','mActivity_m_activity_count']
            feature_dfs.append(agg)
    
    # mLight: m_light
    if 'mLight' in parquet_dfs:
        df = parquet_dfs['mLight'].copy()
        if 'm_light' in df.columns:
            agg = aggregate_numeric(df, 'm_light')
            agg.columns = ['subject_id','date','mLight_m_light_mean','mLight_m_light_std',
                          'mLight_m_light_min','mLight_m_light_max','mLight_m_light_count']
            feature_dfs.append(agg)
    
    # wHr: heart_rate (may be ndarray)
    if 'wHr' in parquet_dfs:
        df = parquet_dfs['wHr'].copy()
        # heart_rate might be ndarray — handle it
        if 'heart_rate' in df.columns:
            hr_vals = []
            for v in df['heart_rate']:
                if isinstance(v, np.ndarray) and len(v) > 0:
                    hr_vals.append(float(v[0]))  # take first value
                elif isinstance(v, (int, float)):
                    hr_vals.append(float(v))
                else:
                    hr_vals.append(np.nan)
            df['hr_flat'] = hr_vals
            agg = aggregate_numeric(df, 'hr_flat')
            agg.columns = ['subject_id','date','wHr_w_hr_mean','wHr_w_hr_std',
                          'wHr_w_hr_min','wHr_w_hr_max','wHr_w_hr_count']
            feature_dfs.append(agg)
    
    # wLight: w_light
    if 'wLight' in parquet_dfs:
        df = parquet_dfs['wLight'].copy()
        if 'w_light' in df.columns:
            agg = aggregate_numeric(df, 'w_light')
            agg.columns = ['subject_id','date','wLight_w_light_mean','wLight_w_light_std',
                          'wLight_w_light_min','wLight_w_light_max','wLight_w_light_count']
            feature_dfs.append(agg)
    
    # wPedo: step, step_frequency, running_step, walking_step, distance, speed, burned_calories
    if 'wPedo' in parquet_dfs:
        df = parquet_dfs['wPedo'].copy()
        pedo_cols = {
            'step': 'wPedo_w_pedometer',
            'step_frequency': 'wPedo_step_frequency',
            'distance': 'wPedo_distance',
            'speed': 'wPedo_speed',
            'burned_calories': 'wPedo_burned_calories',
        }
        for orig_col, prefix in pedo_cols.items():
            if orig_col in df.columns:
                agg = aggregate_numeric(df, orig_col)
                agg.columns = ['subject_id','date',
                              f'{prefix}_mean', f'{prefix}_std',
                              f'{prefix}_min', f'{prefix}_max', f'{prefix}_count']
                feature_dfs.append(agg)
    
    # ── 2. Time-of-day bins for numeric devices ──
    hour_bins = {
        'mACStatus': ('m_charging', 'mACStatus_hour'),
        'mActivity': ('m_activity', 'mActivity_hour'),
        'mLight': ('m_light', 'mLight_hour'),
        'wLight': ('w_light', 'wLight_hour'),
    }
    
    for device, (data_col, prefix) in hour_bins.items():
        if device not in parquet_dfs:
            continue
        df = parquet_dfs[device].copy()
        if 'hour' not in df.columns:
            df['hour'] = pd.to_datetime(df['datetime']).dt.hour
        df['time_bin'] = df['hour'].apply(lambda h: 'night' if h < 6 else 'morning' if h < 12 else 'afternoon' if h < 18 else 'evening')
        time_agg = df.groupby(["subject_id", "date", "time_bin"]).size().unstack(fill_value=0)
        time_agg.columns = [f'{prefix}_{col}' for col in time_agg.columns]
        time_agg = time_agg.reset_index()
        feature_dfs.append(time_agg)
    
    # ── 3. JSON parsing ──
    
    # Ambience
    if 'mAmbience' in parquet_dfs:
        amb_df = parquet_dfs['mAmbience'].copy()
        # Raw parquet has 'm_ambience' column
        if 'm_ambience' in amb_df.columns and 'ambience' not in amb_df.columns:
            amb_df['ambience'] = amb_df['m_ambience']
        amb_parsed = parse_ambience(amb_df)
        if not amb_parsed.empty:
            amb_agg = amb_parsed.groupby(["subject_id", "date", "ambience_value"]).size().unstack(fill_value=0)
            amb_agg.columns = [f"mAmbience_ambience_{col}_sum" for col in amb_agg.columns]
            amb_agg = amb_agg.reset_index()
            feature_dfs.append(amb_agg)
    
    # BLE
    if 'mBle' in parquet_dfs:
        ble_df = parquet_dfs['mBle'].copy()
        ble_df = parse_json_columns(ble_df, ['ble'])
        ble_parsed = parse_ble(ble_df)
        if not ble_parsed.empty:
            for agg_fn in ['mean', 'std', 'min', 'max']:
                if agg_fn == 'mean':
                    agg_df = ble_parsed.groupby(["subject_id", "date"])['rssi'].agg(['mean', 'std', 'min', 'max']).reset_index()
                    agg_df.columns = ['subject_id', 'date', 'mBle_ble_avg_rssi_mean', 'mBle_ble_avg_rssi_std',
                                     'mBle_ble_avg_rssi_min', 'mBle_ble_avg_rssi_max']
                    feature_dfs.append(agg_df)
                elif agg_fn == 'max':
                    agg_df = ble_parsed.groupby(["subject_id", "date"])['rssi'].agg(['max']).reset_index()
                    agg_df.columns = ['subject_id', 'date', 'mBle_ble_max_rssi_mean']
                    feature_dfs.append(agg_df)
                    device_agg = ble_parsed.groupby(["subject_id", "date"])['rssi'].agg(['std']).reset_index()
                    device_agg.columns = ['subject_id', 'date', 'mBle_ble_rssi_std_mean']
                    feature_dfs.append(device_agg)
                    rssi_min_agg = ble_parsed.groupby(["subject_id", "date"])['rssi'].agg(['min', 'std']).reset_index()
                    rssi_min_agg.columns = ['subject_id', 'date', 'mBle_ble_min_rssi_mean', 'mBle_ble_min_rssi_std']
                    feature_dfs.append(rssi_min_agg)
                    rssi_std_agg = ble_parsed.groupby(["subject_id", "date"])['rssi'].agg(['std']).reset_index()
                    rssi_std_agg.columns = ['subject_id', 'date', 'mBle_ble_rssi_std_mean']
                    feature_dfs.append(rssi_std_agg)
    
    # GPS
    if 'mGps' in parquet_dfs:
        gps_df = parquet_dfs['mGps'].copy()
        gps_df = parse_json_columns(gps_df, ['gps'])
        gps_parsed = parse_gps(gps_df)
        if not gps_parsed.empty:
            for col_name, feat_name in [('speed', 'gps_speed'), ('altitude', 'gps_alt')]:
                agg_df = gps_parsed.groupby(["subject_id", "date"])[col_name].agg(['mean', 'std', 'max', 'min']).reset_index()
                agg_df.columns = ['subject_id', 'date',
                                  f'mGps_{feat_name}_mean', f'mGps_{feat_name}_std',
                                  f'mGps_{feat_name}_max', f'mGps_{feat_name}_min']
                feature_dfs.append(agg_df)
            gps_count = gps_parsed.groupby(["subject_id", "date"]).size().reset_index(name='mGps_gps_count_mean')
            feature_dfs.append(gps_count)
    
    # WiFi
    if 'mWifi' in parquet_dfs:
        wifi_df = parquet_dfs['mWifi'].copy()
        wifi_df = parse_json_columns(wifi_df, ['wifi'])
        wifi_parsed = parse_wifi(wifi_df)
        if not wifi_parsed.empty:
            rssi_agg = wifi_parsed.groupby(["subject_id", "date"])['rssi'].agg(['mean', 'std', 'min', 'max']).reset_index()
            rssi_agg.columns = ['subject_id', 'date', 'mWifi_wifi_avg_rssi_mean', 'mWifi_wifi_avg_rssi_std',
                               'mWifi_wifi_avg_rssi_min', 'mWifi_wifi_avg_rssi_max']
            feature_dfs.append(rssi_agg)
            max_rssi_agg = wifi_parsed.groupby(["subject_id", "date"])['rssi'].agg(['max']).reset_index()
            max_rssi_agg.columns = ['subject_id', 'date', 'mWifi_wifi_max_rssi_mean']
            feature_dfs.append(max_rssi_agg)
            strong_mask = wifi_parsed['rssi'] >= -60
            strong_ratio = wifi_parsed.groupby(["subject_id", "date"]).apply(
                lambda x: (strong_mask[x.index].sum() / len(x)) if len(x) > 0 else 0, include_groups=False
            ).reset_index(name='mWifi_wifi_strong_ratio_mean')
            feature_dfs.append(strong_ratio)
            bssid_agg = wifi_parsed.groupby(["subject_id", "date"])['bssid'].nunique().reset_index(name='mWifi_wifi_bssid_count_mean')
            feature_dfs.append(bssid_agg)
            wifi_count = wifi_parsed.groupby(["subject_id", "date"]).size().reset_index(name='mWifi_wifi_count_mean')
            feature_dfs.append(wifi_count)
    
    # UsageStats
    if 'mUsageStats' in parquet_dfs:
        us_df = parquet_dfs['mUsageStats'].copy()
        us_df = parse_json_columns(us_df, ['usage'])
        usage_records = []
        for _, row in us_df.iterrows():
            val = row.get('usage')
            if pd.isna(val) or val == 'null':
                continue
            if isinstance(val, str):
                try: val = json.loads(val)
                except: continue
            if not isinstance(val, list):
                continue
            for item in val:
                if isinstance(item, dict):
                    usage_records.append({
                        'subject_id': row['subject_id'],
                        'datetime': row.get('datetime'),
                        'app_name': item.get('app_name',''),
                        'total_time': item.get('total_time', 0),
                        'category': item.get('category',''),
                        'ratio': item.get('ratio', 0),
                    })
        if usage_records:
            us_df2 = pd.DataFrame(usage_records)
            if not us_df2.empty:
                ratio_agg = us_df2.groupby(["subject_id", "date"])['ratio'].agg(['mean', 'std', 'max']).reset_index()
                ratio_agg.columns = ['subject_id', 'date', 'mUsageStats_usage_ratio_mean',
                                    'mUsageStats_usage_ratio_std', 'mUsageStats_usage_ratio_max']
                feature_dfs.append(ratio_agg)
                time_agg = us_df2.groupby(["subject_id", "date"])['total_time'].agg(['sum', 'mean']).reset_index()
                time_agg.columns = ['subject_id', 'date', 'mUsageStats_usage_total_time_sum',
                                   'mUsageStats_usage_total_time_mean']
                feature_dfs.append(time_agg)
                cat_agg = us_df2.groupby(["subject_id", "date", "category"])['ratio'].sum().reset_index()
                pivoted = cat_agg.pivot_table(index=['subject_id', 'date'], columns='category',
                                              values='ratio', fill_value=0)
                pivoted.columns = [f'mUsageStats_usage_{col}_ratio_sum' for col in pivoted.columns]
                pivoted = pivoted.reset_index()
                feature_dfs.append(pivoted)
    
    # ── 4. ScreenStatus (parse screen_use dict or use numeric) ──
    if 'mScreenStatus' in parquet_dfs:
        ss_df = parquet_dfs['mScreenStatus'].copy()
        # Check if screen_use is already numeric or needs parsing
        sample_val = ss_df['m_screen_use'].iloc[0] if not ss_df.empty else None
        if isinstance(sample_val, dict):
            ss_df = parse_json_columns(ss_df, ['screen_use'])
            ss_parsed = parse_screen_use(ss_df)
            if not ss_parsed.empty:
                ss_agg = ss_parsed.groupby(["subject_id", "date"])['screen_use'].agg(['mean','std','min','max','count']).reset_index()
                ss_agg.columns = ['subject_id','date','mScreenStatus_m_screen_use_mean','mScreenStatus_m_screen_use_std',
                                 'mScreenStatus_m_screen_use_min','mScreenStatus_m_screen_use_max','mScreenStatus_m_screen_use_count']
                feature_dfs.append(ss_agg)
        else:
            # Already numeric (int64)
            agg = aggregate_numeric(ss_df, 'm_screen_use')
            agg.columns = ['subject_id','date','mScreenStatus_m_screen_use_mean','mScreenStatus_m_screen_use_std',
                          'mScreenStatus_m_screen_use_min','mScreenStatus_m_screen_use_max','mScreenStatus_m_screen_use_count']
            feature_dfs.append(agg)
    
    # Time-of-day bins for mScreenStatus
    if 'mScreenStatus' in parquet_dfs:
        ss_df = parquet_dfs['mScreenStatus'].copy()
        if 'hour' not in ss_df.columns:
            ss_df['hour'] = pd.to_datetime(ss_df['datetime']).dt.hour
        ss_df['time_bin'] = ss_df['hour'].apply(lambda h: 'night' if h < 6 else 'morning' if h < 12 else 'afternoon' if h < 18 else 'evening')
        ss_time = ss_df.groupby(["subject_id", "date", "time_bin"]).size().unstack(fill_value=0)
        ss_time.columns = [f'mScreenStatus_hour_{col}' for col in ss_time.columns]
        ss_time = ss_time.reset_index()
        feature_dfs.append(ss_time)
    
    # Time-of-day bins for wPedo
    if 'wPedo' in parquet_dfs:
        pedo_df = parquet_dfs['wPedo'].copy()
        if 'hour' not in pedo_df.columns:
            pedo_df['hour'] = pd.to_datetime(pedo_df['datetime']).dt.hour
        pedo_df['time_bin'] = pedo_df['hour'].apply(lambda h: 'night' if h < 6 else 'morning' if h < 12 else 'afternoon' if h < 18 else 'evening')
        pedo_time = pedo_df.groupby(["subject_id", "date", "time_bin"]).size().unstack(fill_value=0)
        pedo_time.columns = [f'wPedo_hour_{col}' for col in pedo_time.columns]
        pedo_time = pedo_time.reset_index()
        feature_dfs.append(pedo_time)
    
    # ── 5. Merge all ──
    if not feature_dfs:
        return pd.DataFrame()
    
    result = feature_dfs[0]
    for df in feature_dfs[1:]:
        result = result.merge(df, on=['subject_id', 'date'], how='left')
    
    result = result.fillna(0)
    
    # Remove constant cols (from 02_feature_engineering_v2.py)
    CONSTANT_COLS = [
        'mACStatus_m_charging_min', 'mACStatus_m_charging_max',
        'mLight_m_light_min', 'mScreenStatus_m_screen_use_min', 'mScreenStatus_m_screen_use_max',
        'wPedo_w_pedometer_running_step_mean', 'wPedo_w_pedometer_running_step_sum',
        'wPedo_w_pedometer_walking_step_mean', 'wPedo_w_pedometer_walking_step_sum',
        'mGps_gps_has_speed_mean', 'mGps_gps_has_speed_std', 'mGps_gps_has_speed_max', 'mGps_gps_has_speed_min',
        'mUsageStats_usage_major_ratio_min', 'mUsageStats_usage_game_ratio_min',
    ]
    for c in CONSTANT_COLS:
        if c in result.columns:
            result = result.drop(columns=[c])
    
    # Remove collinear pairs (keep first)
    COLLINEAR_PAIRS = [
        ('wPedo_step_frequency_mean', 'wPedo_step_frequency_std'),  # simplified
        ('mBle_ble_device_count_mean', 'mBle_ble_count_mean'),
        ('mBle_ble_device_count_std', 'mBle_ble_count_std'),
        ('mBle_ble_device_count_max', 'mBle_ble_count_max'),
        ('mWifi_wifi_bssid_count_mean', 'mWifi_wifi_count_mean'),
        ('mWifi_wifi_bssid_count_std', 'mWifi_wifi_count_std'),
        ('mWifi_wifi_bssid_count_max', 'mWifi_wifi_count_max'),
    ]
    for col_to_drop, _ in COLLINEAR_PAIRS:
        if col_to_drop in result.columns:
            result = result.drop(columns=[col_to_drop])
    
    return result

def main():
    t0 = time.time()
    print("=" * 70)
    print("gen_v60_train_test.py — Identical train/test feature pipeline")
    print("=" * 70)
    
    # Load labels
    print("\nLoading labels...")
    labels = pd.read_csv(LABEL_CSV, parse_dates=['sleep_date','lifelog_date'])
    print(f"  Labels: {labels.shape}")
    
    # Load sample for test dates
    print("Loading submission sample...")
    sample = pd.read_csv(SAMPLE_CSV, parse_dates=['sleep_date','lifelog_date'])
    sample['date'] = sample['lifelog_date'].dt.date
    print(f"  Sample: {sample.shape}")
    
    # Generate train features
    print("\n── Generating train features ──")
    train_subjects = set(labels['subject_id'].unique())
    train_parquet = load_and_filter_parquet(train_subjects)
    train_feat = create_day_features(train_parquet, labels=labels)
    print(f"  Train shape: {train_feat.shape}")
    
    # Generate test features — ONLY for the exact 250 date pairs in sample
    print("\n── Generating test features ──")
    
    # For test, we need features for only the 250 date pairs in sample_submission
    # Strategy: generate features for sample dates, then filter
    test_subjects = set(sample['subject_id'].unique())
    test_parquet = load_and_filter_parquet(test_subjects)
    
    # Generate features for all dates for these subjects, then filter to sample dates
    test_feat = create_day_features(test_parquet, labels=None)
    
    # Merge with sample to get sleep_date, lifelog_date
    sample_key = sample[['subject_id','date','sleep_date','lifelog_date']]
    test_feat = test_feat.merge(sample_key, on=['subject_id','date'], how='inner')
    
    # Sort to match sample order
    test_feat = test_feat.sort_values(['subject_id', 'date']).reset_index(drop=True)
    
    # Final shape should be 250
    print(f"  Test shape: {test_feat.shape}")
    if len(test_feat) != 250:
        print(f"  ⚠️ WARNING: Expected 250 rows but got {len(test_feat)}")
    
    # Compare columns
    train_cols = sorted([c for c in train_feat.columns if c not in META_COLS | set(TARGETS)])
    test_cols = sorted([c for c in test_feat.columns if c not in META_COLS])
    common_cols = sorted(set(train_cols) & set(test_cols))
    
    print(f"\nTrain features: {len(train_cols)}")
    print(f"Test features: {len(test_cols)}")
    print(f"Common features: {len(common_cols)}")
    
    if set(train_cols) != set(test_cols):
        missing_in_test = sorted(set(train_cols) - set(test_cols))
        extra_in_test = sorted(set(test_cols) - set(train_cols))
        print(f"\nMissing in test: {len(missing_in_test)}")
        for c in missing_in_test[:10]:
            print(f"  {c}")
        print(f"\nExtra in test: {len(extra_in_test)}")
        for c in extra_in_test[:10]:
            print(f"  {c}")
    else:
        print("\n✅ PERFECT MATCH: Train and test have identical column sets!")
    
    # Save
    train_path = DATA / 'train_features_clean_v60.parquet'
    test_path = DATA / 'test_features_clean_v60.parquet'
    
    train_feat.to_parquet(train_path, index=False)
    test_feat.to_parquet(test_path, index=False)
    
    print(f"\nSaved:")
    print(f"  Train: {train_path}")
    print(f"  Test: {test_path}")
    print(f"\nTime: {time.time()-t0:.1f}s")

if __name__ == '__main__':
    main()
